<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class RegencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('regencys')->insert([ 'regency_code'=>1101, 'province_code'=>11, 'regency_name'=>'KABUPATEN SIMEULUE']);
        DB::table('regencys')->insert([ 'regency_code'=>1102, 'province_code'=>11, 'regency_name'=>'KABUPATEN ACEH SINGKIL']);
        DB::table('regencys')->insert([ 'regency_code'=>1103, 'province_code'=>11, 'regency_name'=>'KABUPATEN ACEH SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1104, 'province_code'=>11, 'regency_name'=>'KABUPATEN ACEH TENGGARA']);
        DB::table('regencys')->insert([ 'regency_code'=>1105, 'province_code'=>11, 'regency_name'=>'KABUPATEN ACEH TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>1106, 'province_code'=>11, 'regency_name'=>'KABUPATEN ACEH TENGAH']);
        DB::table('regencys')->insert([ 'regency_code'=>1107, 'province_code'=>11, 'regency_name'=>'KABUPATEN ACEH BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>1108, 'province_code'=>11, 'regency_name'=>'KABUPATEN ACEH BESAR']);
        DB::table('regencys')->insert([ 'regency_code'=>1109, 'province_code'=>11, 'regency_name'=>'KABUPATEN PIDIE']);
        DB::table('regencys')->insert([ 'regency_code'=>1110, 'province_code'=>11, 'regency_name'=>'KABUPATEN BIREUEN']);
        DB::table('regencys')->insert([ 'regency_code'=>1111, 'province_code'=>11, 'regency_name'=>'KABUPATEN ACEH UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>1112, 'province_code'=>11, 'regency_name'=>'KABUPATEN ACEH BARAT DAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>1113, 'province_code'=>11, 'regency_name'=>'KABUPATEN GAYO LUES']);
        DB::table('regencys')->insert([ 'regency_code'=>1114, 'province_code'=>11, 'regency_name'=>'KABUPATEN ACEH TAMIANG']);
        DB::table('regencys')->insert([ 'regency_code'=>1115, 'province_code'=>11, 'regency_name'=>'KABUPATEN NAGAN RAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>1116, 'province_code'=>11, 'regency_name'=>'KABUPATEN ACEH JAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>1117, 'province_code'=>11, 'regency_name'=>'KABUPATEN BENER MERIAH']);
        DB::table('regencys')->insert([ 'regency_code'=>1118, 'province_code'=>11, 'regency_name'=>'KABUPATEN PIDIE JAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>1171, 'province_code'=>11, 'regency_name'=>'KOTA BANDA ACEH']);
        DB::table('regencys')->insert([ 'regency_code'=>1172, 'province_code'=>11, 'regency_name'=>'KOTA SABANG']);
        DB::table('regencys')->insert([ 'regency_code'=>1173, 'province_code'=>11, 'regency_name'=>'KOTA LANGSA']);
        DB::table('regencys')->insert([ 'regency_code'=>1174, 'province_code'=>11, 'regency_name'=>'KOTA LHOKSEUMAWE']);
        DB::table('regencys')->insert([ 'regency_code'=>1175, 'province_code'=>11, 'regency_name'=>'KOTA SUBULUSSALAM']);
        DB::table('regencys')->insert([ 'regency_code'=>1201, 'province_code'=>12, 'regency_name'=>'KABUPATEN NIAS']);
        DB::table('regencys')->insert([ 'regency_code'=>1202, 'province_code'=>12, 'regency_name'=>'KABUPATEN MANDAILING NATAL']);
        DB::table('regencys')->insert([ 'regency_code'=>1203, 'province_code'=>12, 'regency_name'=>'KABUPATEN TAPANULI SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1204, 'province_code'=>12, 'regency_name'=>'KABUPATEN TAPANULI TENGAH']);
        DB::table('regencys')->insert([ 'regency_code'=>1205, 'province_code'=>12, 'regency_name'=>'KABUPATEN TAPANULI UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>1206, 'province_code'=>12, 'regency_name'=>'KABUPATEN TOBA SAMOSIR']);
        DB::table('regencys')->insert([ 'regency_code'=>1207, 'province_code'=>12, 'regency_name'=>'KABUPATEN LABUHAN BATU']);
        DB::table('regencys')->insert([ 'regency_code'=>1208, 'province_code'=>12, 'regency_name'=>'KABUPATEN ASAHAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1209, 'province_code'=>12, 'regency_name'=>'KABUPATEN SIMALUNGUN']);
        DB::table('regencys')->insert([ 'regency_code'=>1210, 'province_code'=>12, 'regency_name'=>'KABUPATEN DAIRI']);
        DB::table('regencys')->insert([ 'regency_code'=>1211, 'province_code'=>12, 'regency_name'=>'KABUPATEN KARO']);
        DB::table('regencys')->insert([ 'regency_code'=>1212, 'province_code'=>12, 'regency_name'=>'KABUPATEN DELI SERDANG']);
        DB::table('regencys')->insert([ 'regency_code'=>1213, 'province_code'=>12, 'regency_name'=>'KABUPATEN LANGKAT']);
        DB::table('regencys')->insert([ 'regency_code'=>1214, 'province_code'=>12, 'regency_name'=>'KABUPATEN NIAS SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1215, 'province_code'=>12, 'regency_name'=>'KABUPATEN HUMBANG HASUNDUTAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1216, 'province_code'=>12, 'regency_name'=>'KABUPATEN PAKPAK BHARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>1217, 'province_code'=>12, 'regency_name'=>'KABUPATEN SAMOSIR']);
        DB::table('regencys')->insert([ 'regency_code'=>1218, 'province_code'=>12, 'regency_name'=>'KABUPATEN SERDANG BEDAGAI']);
        DB::table('regencys')->insert([ 'regency_code'=>1219, 'province_code'=>12, 'regency_name'=>'KABUPATEN BATU BARA']);
        DB::table('regencys')->insert([ 'regency_code'=>1220, 'province_code'=>12, 'regency_name'=>'KABUPATEN PADANG LAWAS UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>1221, 'province_code'=>12, 'regency_name'=>'KABUPATEN PADANG LAWAS']);
        DB::table('regencys')->insert([ 'regency_code'=>1222, 'province_code'=>12, 'regency_name'=>'KABUPATEN LABUHAN BATU SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1223, 'province_code'=>12, 'regency_name'=>'KABUPATEN LABUHAN BATU UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>1224, 'province_code'=>12, 'regency_name'=>'KABUPATEN NIAS UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>1225, 'province_code'=>12, 'regency_name'=>'KABUPATEN NIAS BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>1271, 'province_code'=>12, 'regency_name'=>'KOTA SIBOLGA']);
        DB::table('regencys')->insert([ 'regency_code'=>1272, 'province_code'=>12, 'regency_name'=>'KOTA TANJUNG BALAI']);
        DB::table('regencys')->insert([ 'regency_code'=>1273, 'province_code'=>12, 'regency_name'=>'KOTA PEMATANG SIANTAR']);
        DB::table('regencys')->insert([ 'regency_code'=>1274, 'province_code'=>12, 'regency_name'=>'KOTA TEBING TINGGI']);
        DB::table('regencys')->insert([ 'regency_code'=>1275, 'province_code'=>12, 'regency_name'=>'KOTA MEDAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1276, 'province_code'=>12, 'regency_name'=>'KOTA BINJAI']);
        DB::table('regencys')->insert([ 'regency_code'=>1277, 'province_code'=>12, 'regency_name'=>'KOTA PADANGSIDIMPUAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1278, 'province_code'=>12, 'regency_name'=>'KOTA GUNUNGSITOLI']);
        DB::table('regencys')->insert([ 'regency_code'=>1301, 'province_code'=>13, 'regency_name'=>'KABUPATEN KEPULAUAN MENTAWAI']);
        DB::table('regencys')->insert([ 'regency_code'=>1302, 'province_code'=>13, 'regency_name'=>'KABUPATEN PESISIR SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1303, 'province_code'=>13, 'regency_name'=>'KABUPATEN SOLOK']);
        DB::table('regencys')->insert([ 'regency_code'=>1304, 'province_code'=>13, 'regency_name'=>'KABUPATEN SIJUNJUNG']);
        DB::table('regencys')->insert([ 'regency_code'=>1305, 'province_code'=>13, 'regency_name'=>'KABUPATEN TANAH DATAR']);
        DB::table('regencys')->insert([ 'regency_code'=>1306, 'province_code'=>13, 'regency_name'=>'KABUPATEN PADANG PARIAMAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1307, 'province_code'=>13, 'regency_name'=>'KABUPATEN AGAM']);
        DB::table('regencys')->insert([ 'regency_code'=>1308, 'province_code'=>13, 'regency_name'=>'KABUPATEN LIMA PULUH KOTA']);
        DB::table('regencys')->insert([ 'regency_code'=>1309, 'province_code'=>13, 'regency_name'=>'KABUPATEN PASAMAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1310, 'province_code'=>13, 'regency_name'=>'KABUPATEN SOLOK SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1311, 'province_code'=>13, 'regency_name'=>'KABUPATEN DHARMASRAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>1312, 'province_code'=>13, 'regency_name'=>'KABUPATEN PASAMAN BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>1371, 'province_code'=>13, 'regency_name'=>'KOTA PADANG']);
        DB::table('regencys')->insert([ 'regency_code'=>1372, 'province_code'=>13, 'regency_name'=>'KOTA SOLOK']);
        DB::table('regencys')->insert([ 'regency_code'=>1373, 'province_code'=>13, 'regency_name'=>'KOTA SAWAH LUNTO']);
        DB::table('regencys')->insert([ 'regency_code'=>1374, 'province_code'=>13, 'regency_name'=>'KOTA PADANG PANJANG']);
        DB::table('regencys')->insert([ 'regency_code'=>1375, 'province_code'=>13, 'regency_name'=>'KOTA BUKITTINGGI']);
        DB::table('regencys')->insert([ 'regency_code'=>1376, 'province_code'=>13, 'regency_name'=>'KOTA PAYAKUMBUH']);
        DB::table('regencys')->insert([ 'regency_code'=>1377, 'province_code'=>13, 'regency_name'=>'KOTA PARIAMAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1401, 'province_code'=>14, 'regency_name'=>'KABUPATEN KUANTAN SINGINGI']);
        DB::table('regencys')->insert([ 'regency_code'=>1402, 'province_code'=>14, 'regency_name'=>'KABUPATEN INDRAGIRI HULU']);
        DB::table('regencys')->insert([ 'regency_code'=>1403, 'province_code'=>14, 'regency_name'=>'KABUPATEN INDRAGIRI HILIR']);
        DB::table('regencys')->insert([ 'regency_code'=>1404, 'province_code'=>14, 'regency_name'=>'KABUPATEN PELALAWAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1405, 'province_code'=>14, 'regency_name'=>'KABUPATEN S I A K']);
        DB::table('regencys')->insert([ 'regency_code'=>1406, 'province_code'=>14, 'regency_name'=>'KABUPATEN KAMPAR']);
        DB::table('regencys')->insert([ 'regency_code'=>1407, 'province_code'=>14, 'regency_name'=>'KABUPATEN ROKAN HULU']);
        DB::table('regencys')->insert([ 'regency_code'=>1408, 'province_code'=>14, 'regency_name'=>'KABUPATEN BENGKALIS']);
        DB::table('regencys')->insert([ 'regency_code'=>1409, 'province_code'=>14, 'regency_name'=>'KABUPATEN ROKAN HILIR']);
        DB::table('regencys')->insert([ 'regency_code'=>1410, 'province_code'=>14, 'regency_name'=>'KABUPATEN KEPULAUAN MERANTI']);
        DB::table('regencys')->insert([ 'regency_code'=>1471, 'province_code'=>14, 'regency_name'=>'KOTA PEKANBARU']);
        DB::table('regencys')->insert([ 'regency_code'=>1473, 'province_code'=>14, 'regency_name'=>'KOTA D U M A I']);
        DB::table('regencys')->insert([ 'regency_code'=>1501, 'province_code'=>15, 'regency_name'=>'KABUPATEN KERINCI']);
        DB::table('regencys')->insert([ 'regency_code'=>1502, 'province_code'=>15, 'regency_name'=>'KABUPATEN MERANGIN']);
        DB::table('regencys')->insert([ 'regency_code'=>1503, 'province_code'=>15, 'regency_name'=>'KABUPATEN SAROLANGUN']);
        DB::table('regencys')->insert([ 'regency_code'=>1504, 'province_code'=>15, 'regency_name'=>'KABUPATEN BATANG HARI']);
        DB::table('regencys')->insert([ 'regency_code'=>1505, 'province_code'=>15, 'regency_name'=>'KABUPATEN MUARO JAMBI']);
        DB::table('regencys')->insert([ 'regency_code'=>1506, 'province_code'=>15, 'regency_name'=>'KABUPATEN TANJUNG JABUNG TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>1507, 'province_code'=>15, 'regency_name'=>'KABUPATEN TANJUNG JABUNG BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>1508, 'province_code'=>15, 'regency_name'=>'KABUPATEN TEBO']);
        DB::table('regencys')->insert([ 'regency_code'=>1509, 'province_code'=>15, 'regency_name'=>'KABUPATEN BUNGO']);
        DB::table('regencys')->insert([ 'regency_code'=>1571, 'province_code'=>15, 'regency_name'=>'KOTA JAMBI']);
        DB::table('regencys')->insert([ 'regency_code'=>1572, 'province_code'=>15, 'regency_name'=>'KOTA SUNGAI PENUH']);
        DB::table('regencys')->insert([ 'regency_code'=>1601, 'province_code'=>16, 'regency_name'=>'KABUPATEN OGAN KOMERING ULU']);
        DB::table('regencys')->insert([ 'regency_code'=>1602, 'province_code'=>16, 'regency_name'=>'KABUPATEN OGAN KOMERING ILIR']);
        DB::table('regencys')->insert([ 'regency_code'=>1603, 'province_code'=>16, 'regency_name'=>'KABUPATEN MUARA ENIM']);
        DB::table('regencys')->insert([ 'regency_code'=>1604, 'province_code'=>16, 'regency_name'=>'KABUPATEN LAHAT']);
        DB::table('regencys')->insert([ 'regency_code'=>1605, 'province_code'=>16, 'regency_name'=>'KABUPATEN MUSI RAWAS']);
        DB::table('regencys')->insert([ 'regency_code'=>1606, 'province_code'=>16, 'regency_name'=>'KABUPATEN MUSI BANYUASIN']);
        DB::table('regencys')->insert([ 'regency_code'=>1607, 'province_code'=>16, 'regency_name'=>'KABUPATEN BANYU ASIN']);
        DB::table('regencys')->insert([ 'regency_code'=>1608, 'province_code'=>16, 'regency_name'=>'KABUPATEN OGAN KOMERING ULU SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1609, 'province_code'=>16, 'regency_name'=>'KABUPATEN OGAN KOMERING ULU TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>1610, 'province_code'=>16, 'regency_name'=>'KABUPATEN OGAN ILIR']);
        DB::table('regencys')->insert([ 'regency_code'=>1611, 'province_code'=>16, 'regency_name'=>'KABUPATEN EMPAT LAWANG']);
        DB::table('regencys')->insert([ 'regency_code'=>1612, 'province_code'=>16, 'regency_name'=>'KABUPATEN PENUKAL ABAB LEMATANG ILIR']);
        DB::table('regencys')->insert([ 'regency_code'=>1613, 'province_code'=>16, 'regency_name'=>'KABUPATEN MUSI RAWAS UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>1671, 'province_code'=>16, 'regency_name'=>'KOTA PALEMBANG']);
        DB::table('regencys')->insert([ 'regency_code'=>1672, 'province_code'=>16, 'regency_name'=>'KOTA PRABUMULIH']);
        DB::table('regencys')->insert([ 'regency_code'=>1673, 'province_code'=>16, 'regency_name'=>'KOTA PAGAR ALAM']);
        DB::table('regencys')->insert([ 'regency_code'=>1674, 'province_code'=>16, 'regency_name'=>'KOTA LUBUKLINGGAU']);
        DB::table('regencys')->insert([ 'regency_code'=>1701, 'province_code'=>17, 'regency_name'=>'KABUPATEN BENGKULU SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1702, 'province_code'=>17, 'regency_name'=>'KABUPATEN REJANG LEBONG']);
        DB::table('regencys')->insert([ 'regency_code'=>1703, 'province_code'=>17, 'regency_name'=>'KABUPATEN BENGKULU UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>1704, 'province_code'=>17, 'regency_name'=>'KABUPATEN KAUR']);
        DB::table('regencys')->insert([ 'regency_code'=>1705, 'province_code'=>17, 'regency_name'=>'KABUPATEN SELUMA']);
        DB::table('regencys')->insert([ 'regency_code'=>1706, 'province_code'=>17, 'regency_name'=>'KABUPATEN MUKOMUKO']);
        DB::table('regencys')->insert([ 'regency_code'=>1707, 'province_code'=>17, 'regency_name'=>'KABUPATEN LEBONG']);
        DB::table('regencys')->insert([ 'regency_code'=>1708, 'province_code'=>17, 'regency_name'=>'KABUPATEN KEPAHIANG']);
        DB::table('regencys')->insert([ 'regency_code'=>1709, 'province_code'=>17, 'regency_name'=>'KABUPATEN BENGKULU TENGAH']);
        DB::table('regencys')->insert([ 'regency_code'=>1771, 'province_code'=>17, 'regency_name'=>'KOTA BENGKULU']);
        DB::table('regencys')->insert([ 'regency_code'=>1801, 'province_code'=>18, 'regency_name'=>'KABUPATEN LAMPUNG BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>1802, 'province_code'=>18, 'regency_name'=>'KABUPATEN TANGGAMUS']);
        DB::table('regencys')->insert([ 'regency_code'=>1803, 'province_code'=>18, 'regency_name'=>'KABUPATEN LAMPUNG SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1804, 'province_code'=>18, 'regency_name'=>'KABUPATEN LAMPUNG TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>1805, 'province_code'=>18, 'regency_name'=>'KABUPATEN LAMPUNG TENGAH']);
        DB::table('regencys')->insert([ 'regency_code'=>1806, 'province_code'=>18, 'regency_name'=>'KABUPATEN LAMPUNG UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>1807, 'province_code'=>18, 'regency_name'=>'KABUPATEN WAY KANAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1808, 'province_code'=>18, 'regency_name'=>'KABUPATEN TULANGBAWANG']);
        DB::table('regencys')->insert([ 'regency_code'=>1809, 'province_code'=>18, 'regency_name'=>'KABUPATEN PESAWARAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1810, 'province_code'=>18, 'regency_name'=>'KABUPATEN PRINGSEWU']);
        DB::table('regencys')->insert([ 'regency_code'=>1811, 'province_code'=>18, 'regency_name'=>'KABUPATEN MESUJI']);
        DB::table('regencys')->insert([ 'regency_code'=>1812, 'province_code'=>18, 'regency_name'=>'KABUPATEN TULANG BAWANG BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>1813, 'province_code'=>18, 'regency_name'=>'KABUPATEN PESISIR BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>1871, 'province_code'=>18, 'regency_name'=>'KOTA BANDAR LAMPUNG']);
        DB::table('regencys')->insert([ 'regency_code'=>1872, 'province_code'=>18, 'regency_name'=>'KOTA METRO']);
        DB::table('regencys')->insert([ 'regency_code'=>1901, 'province_code'=>19, 'regency_name'=>'KABUPATEN BANGKA']);
        DB::table('regencys')->insert([ 'regency_code'=>1902, 'province_code'=>19, 'regency_name'=>'KABUPATEN BELITUNG']);
        DB::table('regencys')->insert([ 'regency_code'=>1903, 'province_code'=>19, 'regency_name'=>'KABUPATEN BANGKA BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>1904, 'province_code'=>19, 'regency_name'=>'KABUPATEN BANGKA TENGAH']);
        DB::table('regencys')->insert([ 'regency_code'=>1905, 'province_code'=>19, 'regency_name'=>'KABUPATEN BANGKA SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>1906, 'province_code'=>19, 'regency_name'=>'KABUPATEN BELITUNG TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>1971, 'province_code'=>19, 'regency_name'=>'KOTA PANGKAL PINANG']);
        DB::table('regencys')->insert([ 'regency_code'=>2101, 'province_code'=>21, 'regency_name'=>'KABUPATEN KARIMUN']);
        DB::table('regencys')->insert([ 'regency_code'=>2102, 'province_code'=>21, 'regency_name'=>'KABUPATEN BINTAN']);
        DB::table('regencys')->insert([ 'regency_code'=>2103, 'province_code'=>21, 'regency_name'=>'KABUPATEN NATUNA']);
        DB::table('regencys')->insert([ 'regency_code'=>2104, 'province_code'=>21, 'regency_name'=>'KABUPATEN LINGGA']);
        DB::table('regencys')->insert([ 'regency_code'=>2105, 'province_code'=>21, 'regency_name'=>'KABUPATEN KEPULAUAN ANAMBAS']);
        DB::table('regencys')->insert([ 'regency_code'=>2171, 'province_code'=>21, 'regency_name'=>'KOTA B A T A M']);
        DB::table('regencys')->insert([ 'regency_code'=>2172, 'province_code'=>21, 'regency_name'=>'KOTA TANJUNG PINANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3101, 'province_code'=>31, 'regency_name'=>'KABUPATEN KEPULAUAN SERIBU']);
        DB::table('regencys')->insert([ 'regency_code'=>3171, 'province_code'=>31, 'regency_name'=>'KOTA JAKARTA SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>3172, 'province_code'=>31, 'regency_name'=>'KOTA JAKARTA TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>3173, 'province_code'=>31, 'regency_name'=>'KOTA JAKARTA PUSAT']);
        DB::table('regencys')->insert([ 'regency_code'=>3174, 'province_code'=>31, 'regency_name'=>'KOTA JAKARTA BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>3175, 'province_code'=>31, 'regency_name'=>'KOTA JAKARTA UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>3201, 'province_code'=>32, 'regency_name'=>'KABUPATEN BOGOR']);
        DB::table('regencys')->insert([ 'regency_code'=>3202, 'province_code'=>32, 'regency_name'=>'KABUPATEN SUKABUMI']);
        DB::table('regencys')->insert([ 'regency_code'=>3203, 'province_code'=>32, 'regency_name'=>'KABUPATEN CIANJUR']);
        DB::table('regencys')->insert([ 'regency_code'=>3204, 'province_code'=>32, 'regency_name'=>'KABUPATEN BANDUNG']);
        DB::table('regencys')->insert([ 'regency_code'=>3205, 'province_code'=>32, 'regency_name'=>'KABUPATEN GARUT']);
        DB::table('regencys')->insert([ 'regency_code'=>3206, 'province_code'=>32, 'regency_name'=>'KABUPATEN TASIKMALAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>3207, 'province_code'=>32, 'regency_name'=>'KABUPATEN CIAMIS']);
        DB::table('regencys')->insert([ 'regency_code'=>3208, 'province_code'=>32, 'regency_name'=>'KABUPATEN KUNINGAN']);
        DB::table('regencys')->insert([ 'regency_code'=>3209, 'province_code'=>32, 'regency_name'=>'KABUPATEN CIREBON']);
        DB::table('regencys')->insert([ 'regency_code'=>3210, 'province_code'=>32, 'regency_name'=>'KABUPATEN MAJALENGKA']);
        DB::table('regencys')->insert([ 'regency_code'=>3211, 'province_code'=>32, 'regency_name'=>'KABUPATEN SUMEDANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3212, 'province_code'=>32, 'regency_name'=>'KABUPATEN INDRAMAYU']);
        DB::table('regencys')->insert([ 'regency_code'=>3213, 'province_code'=>32, 'regency_name'=>'KABUPATEN SUBANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3214, 'province_code'=>32, 'regency_name'=>'KABUPATEN PURWAKARTA']);
        DB::table('regencys')->insert([ 'regency_code'=>3215, 'province_code'=>32, 'regency_name'=>'KABUPATEN KARAWANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3216, 'province_code'=>32, 'regency_name'=>'KABUPATEN BEKASI']);
        DB::table('regencys')->insert([ 'regency_code'=>3217, 'province_code'=>32, 'regency_name'=>'KABUPATEN BANDUNG BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>3218, 'province_code'=>32, 'regency_name'=>'KABUPATEN PANGANDARAN']);
        DB::table('regencys')->insert([ 'regency_code'=>3271, 'province_code'=>32, 'regency_name'=>'KOTA BOGOR']);
        DB::table('regencys')->insert([ 'regency_code'=>3272, 'province_code'=>32, 'regency_name'=>'KOTA SUKABUMI']);
        DB::table('regencys')->insert([ 'regency_code'=>3273, 'province_code'=>32, 'regency_name'=>'KOTA BANDUNG']);
        DB::table('regencys')->insert([ 'regency_code'=>3274, 'province_code'=>32, 'regency_name'=>'KOTA CIREBON']);
        DB::table('regencys')->insert([ 'regency_code'=>3275, 'province_code'=>32, 'regency_name'=>'KOTA BEKASI']);
        DB::table('regencys')->insert([ 'regency_code'=>3276, 'province_code'=>32, 'regency_name'=>'KOTA DEPOK']);
        DB::table('regencys')->insert([ 'regency_code'=>3277, 'province_code'=>32, 'regency_name'=>'KOTA CIMAHI']);
        DB::table('regencys')->insert([ 'regency_code'=>3278, 'province_code'=>32, 'regency_name'=>'KOTA TASIKMALAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>3279, 'province_code'=>32, 'regency_name'=>'KOTA BANJAR']);
        DB::table('regencys')->insert([ 'regency_code'=>3301, 'province_code'=>33, 'regency_name'=>'KABUPATEN CILACAP']);
        DB::table('regencys')->insert([ 'regency_code'=>3302, 'province_code'=>33, 'regency_name'=>'KABUPATEN BANYUMAS']);
        DB::table('regencys')->insert([ 'regency_code'=>3303, 'province_code'=>33, 'regency_name'=>'KABUPATEN PURBALINGGA']);
        DB::table('regencys')->insert([ 'regency_code'=>3304, 'province_code'=>33, 'regency_name'=>'KABUPATEN BANJARNEGARA']);
        DB::table('regencys')->insert([ 'regency_code'=>3305, 'province_code'=>33, 'regency_name'=>'KABUPATEN KEBUMEN']);
        DB::table('regencys')->insert([ 'regency_code'=>3306, 'province_code'=>33, 'regency_name'=>'KABUPATEN PURWOREJO']);
        DB::table('regencys')->insert([ 'regency_code'=>3307, 'province_code'=>33, 'regency_name'=>'KABUPATEN WONOSOBO']);
        DB::table('regencys')->insert([ 'regency_code'=>3308, 'province_code'=>33, 'regency_name'=>'KABUPATEN MAGELANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3309, 'province_code'=>33, 'regency_name'=>'KABUPATEN BOYOLALI']);
        DB::table('regencys')->insert([ 'regency_code'=>3310, 'province_code'=>33, 'regency_name'=>'KABUPATEN KLATEN']);
        DB::table('regencys')->insert([ 'regency_code'=>3311, 'province_code'=>33, 'regency_name'=>'KABUPATEN SUKOHARJO']);
        DB::table('regencys')->insert([ 'regency_code'=>3312, 'province_code'=>33, 'regency_name'=>'KABUPATEN WONOGIRI']);
        DB::table('regencys')->insert([ 'regency_code'=>3313, 'province_code'=>33, 'regency_name'=>'KABUPATEN KARANGANYAR']);
        DB::table('regencys')->insert([ 'regency_code'=>3314, 'province_code'=>33, 'regency_name'=>'KABUPATEN SRAGEN']);
        DB::table('regencys')->insert([ 'regency_code'=>3315, 'province_code'=>33, 'regency_name'=>'KABUPATEN GROBOGAN']);
        DB::table('regencys')->insert([ 'regency_code'=>3316, 'province_code'=>33, 'regency_name'=>'KABUPATEN BLORA']);
        DB::table('regencys')->insert([ 'regency_code'=>3317, 'province_code'=>33, 'regency_name'=>'KABUPATEN REMBANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3318, 'province_code'=>33, 'regency_name'=>'KABUPATEN PATI']);
        DB::table('regencys')->insert([ 'regency_code'=>3319, 'province_code'=>33, 'regency_name'=>'KABUPATEN KUDUS']);
        DB::table('regencys')->insert([ 'regency_code'=>3320, 'province_code'=>33, 'regency_name'=>'KABUPATEN JEPARA']);
        DB::table('regencys')->insert([ 'regency_code'=>3321, 'province_code'=>33, 'regency_name'=>'KABUPATEN DEMAK']);
        DB::table('regencys')->insert([ 'regency_code'=>3322, 'province_code'=>33, 'regency_name'=>'KABUPATEN SEMARANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3323, 'province_code'=>33, 'regency_name'=>'KABUPATEN TEMANGGUNG']);
        DB::table('regencys')->insert([ 'regency_code'=>3324, 'province_code'=>33, 'regency_name'=>'KABUPATEN KENDAL']);
        DB::table('regencys')->insert([ 'regency_code'=>3325, 'province_code'=>33, 'regency_name'=>'KABUPATEN BATANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3326, 'province_code'=>33, 'regency_name'=>'KABUPATEN PEKALONGAN']);
        DB::table('regencys')->insert([ 'regency_code'=>3327, 'province_code'=>33, 'regency_name'=>'KABUPATEN PEMALANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3328, 'province_code'=>33, 'regency_name'=>'KABUPATEN TEGAL']);
        DB::table('regencys')->insert([ 'regency_code'=>3329, 'province_code'=>33, 'regency_name'=>'KABUPATEN BREBES']);
        DB::table('regencys')->insert([ 'regency_code'=>3371, 'province_code'=>33, 'regency_name'=>'KOTA MAGELANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3372, 'province_code'=>33, 'regency_name'=>'KOTA SURAKARTA']);
        DB::table('regencys')->insert([ 'regency_code'=>3373, 'province_code'=>33, 'regency_name'=>'KOTA SALATIGA']);
        DB::table('regencys')->insert([ 'regency_code'=>3374, 'province_code'=>33, 'regency_name'=>'KOTA SEMARANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3375, 'province_code'=>33, 'regency_name'=>'KOTA PEKALONGAN']);
        DB::table('regencys')->insert([ 'regency_code'=>3376, 'province_code'=>33, 'regency_name'=>'KOTA TEGAL']);
        DB::table('regencys')->insert([ 'regency_code'=>3401, 'province_code'=>34, 'regency_name'=>'KABUPATEN KULON PROGO']);
        DB::table('regencys')->insert([ 'regency_code'=>3402, 'province_code'=>34, 'regency_name'=>'KABUPATEN BANTUL']);
        DB::table('regencys')->insert([ 'regency_code'=>3403, 'province_code'=>34, 'regency_name'=>'KABUPATEN GUNUNG KIDUL']);
        DB::table('regencys')->insert([ 'regency_code'=>3404, 'province_code'=>34, 'regency_name'=>'KABUPATEN SLEMAN']);
        DB::table('regencys')->insert([ 'regency_code'=>3471, 'province_code'=>34, 'regency_name'=>'KOTA YOGYAKARTA']);
        DB::table('regencys')->insert([ 'regency_code'=>3501, 'province_code'=>35, 'regency_name'=>'KABUPATEN PACITAN']);
        DB::table('regencys')->insert([ 'regency_code'=>3502, 'province_code'=>35, 'regency_name'=>'KABUPATEN PONOROGO']);
        DB::table('regencys')->insert([ 'regency_code'=>3503, 'province_code'=>35, 'regency_name'=>'KABUPATEN TRENGGALEK']);
        DB::table('regencys')->insert([ 'regency_code'=>3504, 'province_code'=>35, 'regency_name'=>'KABUPATEN TULUNGAGUNG']);
        DB::table('regencys')->insert([ 'regency_code'=>3505, 'province_code'=>35, 'regency_name'=>'KABUPATEN BLITAR']);
        DB::table('regencys')->insert([ 'regency_code'=>3506, 'province_code'=>35, 'regency_name'=>'KABUPATEN KEDIRI']);
        DB::table('regencys')->insert([ 'regency_code'=>3507, 'province_code'=>35, 'regency_name'=>'KABUPATEN MALANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3508, 'province_code'=>35, 'regency_name'=>'KABUPATEN LUMAJANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3509, 'province_code'=>35, 'regency_name'=>'KABUPATEN JEMBER']);
        DB::table('regencys')->insert([ 'regency_code'=>3510, 'province_code'=>35, 'regency_name'=>'KABUPATEN BANYUWANGI']);
        DB::table('regencys')->insert([ 'regency_code'=>3511, 'province_code'=>35, 'regency_name'=>'KABUPATEN BONDOWOSO']);
        DB::table('regencys')->insert([ 'regency_code'=>3512, 'province_code'=>35, 'regency_name'=>'KABUPATEN SITUBONDO']);
        DB::table('regencys')->insert([ 'regency_code'=>3513, 'province_code'=>35, 'regency_name'=>'KABUPATEN PROBOLINGGO']);
        DB::table('regencys')->insert([ 'regency_code'=>3514, 'province_code'=>35, 'regency_name'=>'KABUPATEN PASURUAN']);
        DB::table('regencys')->insert([ 'regency_code'=>3515, 'province_code'=>35, 'regency_name'=>'KABUPATEN SIDOARJO']);
        DB::table('regencys')->insert([ 'regency_code'=>3516, 'province_code'=>35, 'regency_name'=>'KABUPATEN MOJOKERTO']);
        DB::table('regencys')->insert([ 'regency_code'=>3517, 'province_code'=>35, 'regency_name'=>'KABUPATEN JOMBANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3518, 'province_code'=>35, 'regency_name'=>'KABUPATEN NGANJUK']);
        DB::table('regencys')->insert([ 'regency_code'=>3519, 'province_code'=>35, 'regency_name'=>'KABUPATEN MADIUN']);
        DB::table('regencys')->insert([ 'regency_code'=>3520, 'province_code'=>35, 'regency_name'=>'KABUPATEN MAGETAN']);
        DB::table('regencys')->insert([ 'regency_code'=>3521, 'province_code'=>35, 'regency_name'=>'KABUPATEN NGAWI']);
        DB::table('regencys')->insert([ 'regency_code'=>3522, 'province_code'=>35, 'regency_name'=>'KABUPATEN BOJONEGORO']);
        DB::table('regencys')->insert([ 'regency_code'=>3523, 'province_code'=>35, 'regency_name'=>'KABUPATEN TUBAN']);
        DB::table('regencys')->insert([ 'regency_code'=>3524, 'province_code'=>35, 'regency_name'=>'KABUPATEN LAMONGAN']);
        DB::table('regencys')->insert([ 'regency_code'=>3525, 'province_code'=>35, 'regency_name'=>'KABUPATEN GRESIK']);
        DB::table('regencys')->insert([ 'regency_code'=>3526, 'province_code'=>35, 'regency_name'=>'KABUPATEN BANGKALAN']);
        DB::table('regencys')->insert([ 'regency_code'=>3527, 'province_code'=>35, 'regency_name'=>'KABUPATEN SAMPANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3528, 'province_code'=>35, 'regency_name'=>'KABUPATEN PAMEKASAN']);
        DB::table('regencys')->insert([ 'regency_code'=>3529, 'province_code'=>35, 'regency_name'=>'KABUPATEN SUMENEP']);
        DB::table('regencys')->insert([ 'regency_code'=>3571, 'province_code'=>35, 'regency_name'=>'KOTA KEDIRI']);
        DB::table('regencys')->insert([ 'regency_code'=>3572, 'province_code'=>35, 'regency_name'=>'KOTA BLITAR']);
        DB::table('regencys')->insert([ 'regency_code'=>3573, 'province_code'=>35, 'regency_name'=>'KOTA MALANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3574, 'province_code'=>35, 'regency_name'=>'KOTA PROBOLINGGO']);
        DB::table('regencys')->insert([ 'regency_code'=>3575, 'province_code'=>35, 'regency_name'=>'KOTA PASURUAN']);
        DB::table('regencys')->insert([ 'regency_code'=>3576, 'province_code'=>35, 'regency_name'=>'KOTA MOJOKERTO']);
        DB::table('regencys')->insert([ 'regency_code'=>3577, 'province_code'=>35, 'regency_name'=>'KOTA MADIUN']);
        DB::table('regencys')->insert([ 'regency_code'=>3578, 'province_code'=>35, 'regency_name'=>'KOTA SURABAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>3579, 'province_code'=>35, 'regency_name'=>'KOTA BATU']);
        DB::table('regencys')->insert([ 'regency_code'=>3601, 'province_code'=>36, 'regency_name'=>'KABUPATEN PANDEGLANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3602, 'province_code'=>36, 'regency_name'=>'KABUPATEN LEBAK']);
        DB::table('regencys')->insert([ 'regency_code'=>3603, 'province_code'=>36, 'regency_name'=>'KABUPATEN TANGERANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3604, 'province_code'=>36, 'regency_name'=>'KABUPATEN SERANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3671, 'province_code'=>36, 'regency_name'=>'KOTA TANGERANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3672, 'province_code'=>36, 'regency_name'=>'KOTA CILEGON']);
        DB::table('regencys')->insert([ 'regency_code'=>3673, 'province_code'=>36, 'regency_name'=>'KOTA SERANG']);
        DB::table('regencys')->insert([ 'regency_code'=>3674, 'province_code'=>36, 'regency_name'=>'KOTA TANGERANG SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>5101, 'province_code'=>51, 'regency_name'=>'KABUPATEN JEMBRANA']);
        DB::table('regencys')->insert([ 'regency_code'=>5102, 'province_code'=>51, 'regency_name'=>'KABUPATEN TABANAN']);
        DB::table('regencys')->insert([ 'regency_code'=>5103, 'province_code'=>51, 'regency_name'=>'KABUPATEN BADUNG']);
        DB::table('regencys')->insert([ 'regency_code'=>5104, 'province_code'=>51, 'regency_name'=>'KABUPATEN GIANYAR']);
        DB::table('regencys')->insert([ 'regency_code'=>5105, 'province_code'=>51, 'regency_name'=>'KABUPATEN KLUNGKUNG']);
        DB::table('regencys')->insert([ 'regency_code'=>5106, 'province_code'=>51, 'regency_name'=>'KABUPATEN BANGLI']);
        DB::table('regencys')->insert([ 'regency_code'=>5107, 'province_code'=>51, 'regency_name'=>'KABUPATEN KARANG ASEM']);
        DB::table('regencys')->insert([ 'regency_code'=>5108, 'province_code'=>51, 'regency_name'=>'KABUPATEN BULELENG']);
        DB::table('regencys')->insert([ 'regency_code'=>5171, 'province_code'=>51, 'regency_name'=>'KOTA DENPASAR']);
        DB::table('regencys')->insert([ 'regency_code'=>5201, 'province_code'=>52, 'regency_name'=>'KABUPATEN LOMBOK BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>5202, 'province_code'=>52, 'regency_name'=>'KABUPATEN LOMBOK TENGAH']);
        DB::table('regencys')->insert([ 'regency_code'=>5203, 'province_code'=>52, 'regency_name'=>'KABUPATEN LOMBOK TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>5204, 'province_code'=>52, 'regency_name'=>'KABUPATEN SUMBAWA']);
        DB::table('regencys')->insert([ 'regency_code'=>5205, 'province_code'=>52, 'regency_name'=>'KABUPATEN DOMPU']);
        DB::table('regencys')->insert([ 'regency_code'=>5206, 'province_code'=>52, 'regency_name'=>'KABUPATEN BIMA']);
        DB::table('regencys')->insert([ 'regency_code'=>5207, 'province_code'=>52, 'regency_name'=>'KABUPATEN SUMBAWA BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>5208, 'province_code'=>52, 'regency_name'=>'KABUPATEN LOMBOK UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>5271, 'province_code'=>52, 'regency_name'=>'KOTA MATARAM']);
        DB::table('regencys')->insert([ 'regency_code'=>5272, 'province_code'=>52, 'regency_name'=>'KOTA BIMA']);
        DB::table('regencys')->insert([ 'regency_code'=>5301, 'province_code'=>53, 'regency_name'=>'KABUPATEN SUMBA BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>5302, 'province_code'=>53, 'regency_name'=>'KABUPATEN SUMBA TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>5303, 'province_code'=>53, 'regency_name'=>'KABUPATEN KUPANG']);
        DB::table('regencys')->insert([ 'regency_code'=>5304, 'province_code'=>53, 'regency_name'=>'KABUPATEN TIMOR TENGAH SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>5305, 'province_code'=>53, 'regency_name'=>'KABUPATEN TIMOR TENGAH UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>5306, 'province_code'=>53, 'regency_name'=>'KABUPATEN BELU']);
        DB::table('regencys')->insert([ 'regency_code'=>5307, 'province_code'=>53, 'regency_name'=>'KABUPATEN ALOR']);
        DB::table('regencys')->insert([ 'regency_code'=>5308, 'province_code'=>53, 'regency_name'=>'KABUPATEN LEMBATA']);
        DB::table('regencys')->insert([ 'regency_code'=>5309, 'province_code'=>53, 'regency_name'=>'KABUPATEN FLORES TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>5310, 'province_code'=>53, 'regency_name'=>'KABUPATEN SIKKA']);
        DB::table('regencys')->insert([ 'regency_code'=>5311, 'province_code'=>53, 'regency_name'=>'KABUPATEN ENDE']);
        DB::table('regencys')->insert([ 'regency_code'=>5312, 'province_code'=>53, 'regency_name'=>'KABUPATEN NGADA']);
        DB::table('regencys')->insert([ 'regency_code'=>5313, 'province_code'=>53, 'regency_name'=>'KABUPATEN MANGGARAI']);
        DB::table('regencys')->insert([ 'regency_code'=>5314, 'province_code'=>53, 'regency_name'=>'KABUPATEN ROTE NDAO']);
        DB::table('regencys')->insert([ 'regency_code'=>5315, 'province_code'=>53, 'regency_name'=>'KABUPATEN MANGGARAI BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>5316, 'province_code'=>53, 'regency_name'=>'KABUPATEN SUMBA TENGAH']);
        DB::table('regencys')->insert([ 'regency_code'=>5317, 'province_code'=>53, 'regency_name'=>'KABUPATEN SUMBA BARAT DAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>5318, 'province_code'=>53, 'regency_name'=>'KABUPATEN NAGEKEO']);
        DB::table('regencys')->insert([ 'regency_code'=>5319, 'province_code'=>53, 'regency_name'=>'KABUPATEN MANGGARAI TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>5320, 'province_code'=>53, 'regency_name'=>'KABUPATEN SABU RAIJUA']);
        DB::table('regencys')->insert([ 'regency_code'=>5321, 'province_code'=>53, 'regency_name'=>'KABUPATEN MALAKA']);
        DB::table('regencys')->insert([ 'regency_code'=>5371, 'province_code'=>53, 'regency_name'=>'KOTA KUPANG']);
        DB::table('regencys')->insert([ 'regency_code'=>6101, 'province_code'=>61, 'regency_name'=>'KABUPATEN SAMBAS']);
        DB::table('regencys')->insert([ 'regency_code'=>6102, 'province_code'=>61, 'regency_name'=>'KABUPATEN BENGKAYANG']);
        DB::table('regencys')->insert([ 'regency_code'=>6103, 'province_code'=>61, 'regency_name'=>'KABUPATEN LANDAK']);
        DB::table('regencys')->insert([ 'regency_code'=>6104, 'province_code'=>61, 'regency_name'=>'KABUPATEN MEMPAWAH']);
        DB::table('regencys')->insert([ 'regency_code'=>6105, 'province_code'=>61, 'regency_name'=>'KABUPATEN SANGGAU']);
        DB::table('regencys')->insert([ 'regency_code'=>6106, 'province_code'=>61, 'regency_name'=>'KABUPATEN KETAPANG']);
        DB::table('regencys')->insert([ 'regency_code'=>6107, 'province_code'=>61, 'regency_name'=>'KABUPATEN SINTANG']);
        DB::table('regencys')->insert([ 'regency_code'=>6108, 'province_code'=>61, 'regency_name'=>'KABUPATEN KAPUAS HULU']);
        DB::table('regencys')->insert([ 'regency_code'=>6109, 'province_code'=>61, 'regency_name'=>'KABUPATEN SEKADAU']);
        DB::table('regencys')->insert([ 'regency_code'=>6110, 'province_code'=>61, 'regency_name'=>'KABUPATEN MELAWI']);
        DB::table('regencys')->insert([ 'regency_code'=>6111, 'province_code'=>61, 'regency_name'=>'KABUPATEN KAYONG UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>6112, 'province_code'=>61, 'regency_name'=>'KABUPATEN KUBU RAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>6171, 'province_code'=>61, 'regency_name'=>'KOTA PONTIANAK']);
        DB::table('regencys')->insert([ 'regency_code'=>6172, 'province_code'=>61, 'regency_name'=>'KOTA SINGKAWANG']);
        DB::table('regencys')->insert([ 'regency_code'=>6201, 'province_code'=>62, 'regency_name'=>'KABUPATEN KOTAWARINGIN BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>6202, 'province_code'=>62, 'regency_name'=>'KABUPATEN KOTAWARINGIN TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>6203, 'province_code'=>62, 'regency_name'=>'KABUPATEN KAPUAS']);
        DB::table('regencys')->insert([ 'regency_code'=>6204, 'province_code'=>62, 'regency_name'=>'KABUPATEN BARITO SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>6205, 'province_code'=>62, 'regency_name'=>'KABUPATEN BARITO UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>6206, 'province_code'=>62, 'regency_name'=>'KABUPATEN SUKAMARA']);
        DB::table('regencys')->insert([ 'regency_code'=>6207, 'province_code'=>62, 'regency_name'=>'KABUPATEN LAMANDAU']);
        DB::table('regencys')->insert([ 'regency_code'=>6208, 'province_code'=>62, 'regency_name'=>'KABUPATEN SERUYAN']);
        DB::table('regencys')->insert([ 'regency_code'=>6209, 'province_code'=>62, 'regency_name'=>'KABUPATEN KATINGAN']);
        DB::table('regencys')->insert([ 'regency_code'=>6210, 'province_code'=>62, 'regency_name'=>'KABUPATEN PULANG PISAU']);
        DB::table('regencys')->insert([ 'regency_code'=>6211, 'province_code'=>62, 'regency_name'=>'KABUPATEN GUNUNG MAS']);
        DB::table('regencys')->insert([ 'regency_code'=>6212, 'province_code'=>62, 'regency_name'=>'KABUPATEN BARITO TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>6213, 'province_code'=>62, 'regency_name'=>'KABUPATEN MURUNG RAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>6271, 'province_code'=>62, 'regency_name'=>'KOTA PALANGKA RAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>6301, 'province_code'=>63, 'regency_name'=>'KABUPATEN TANAH LAUT']);
        DB::table('regencys')->insert([ 'regency_code'=>6302, 'province_code'=>63, 'regency_name'=>'KABUPATEN KOTA BARU']);
        DB::table('regencys')->insert([ 'regency_code'=>6303, 'province_code'=>63, 'regency_name'=>'KABUPATEN BANJAR']);
        DB::table('regencys')->insert([ 'regency_code'=>6304, 'province_code'=>63, 'regency_name'=>'KABUPATEN BARITO KUALA']);
        DB::table('regencys')->insert([ 'regency_code'=>6305, 'province_code'=>63, 'regency_name'=>'KABUPATEN TAPIN']);
        DB::table('regencys')->insert([ 'regency_code'=>6306, 'province_code'=>63, 'regency_name'=>'KABUPATEN HULU SUNGAI SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>6307, 'province_code'=>63, 'regency_name'=>'KABUPATEN HULU SUNGAI TENGAH']);
        DB::table('regencys')->insert([ 'regency_code'=>6308, 'province_code'=>63, 'regency_name'=>'KABUPATEN HULU SUNGAI UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>6309, 'province_code'=>63, 'regency_name'=>'KABUPATEN TABALONG']);
        DB::table('regencys')->insert([ 'regency_code'=>6310, 'province_code'=>63, 'regency_name'=>'KABUPATEN TANAH BUMBU']);
        DB::table('regencys')->insert([ 'regency_code'=>6311, 'province_code'=>63, 'regency_name'=>'KABUPATEN BALANGAN']);
        DB::table('regencys')->insert([ 'regency_code'=>6371, 'province_code'=>63, 'regency_name'=>'KOTA BANJARMASIN']);
        DB::table('regencys')->insert([ 'regency_code'=>6372, 'province_code'=>63, 'regency_name'=>'KOTA BANJAR BARU']);
        DB::table('regencys')->insert([ 'regency_code'=>6401, 'province_code'=>64, 'regency_name'=>'KABUPATEN PASER']);
        DB::table('regencys')->insert([ 'regency_code'=>6402, 'province_code'=>64, 'regency_name'=>'KABUPATEN KUTAI BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>6403, 'province_code'=>64, 'regency_name'=>'KABUPATEN KUTAI KARTANEGARA']);
        DB::table('regencys')->insert([ 'regency_code'=>6404, 'province_code'=>64, 'regency_name'=>'KABUPATEN KUTAI TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>6405, 'province_code'=>64, 'regency_name'=>'KABUPATEN BERAU']);
        DB::table('regencys')->insert([ 'regency_code'=>6409, 'province_code'=>64, 'regency_name'=>'KABUPATEN PENAJAM PASER UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>6411, 'province_code'=>64, 'regency_name'=>'KABUPATEN MAHAKAM HULU']);
        DB::table('regencys')->insert([ 'regency_code'=>6471, 'province_code'=>64, 'regency_name'=>'KOTA BALIKPAPAN']);
        DB::table('regencys')->insert([ 'regency_code'=>6472, 'province_code'=>64, 'regency_name'=>'KOTA SAMARINDA']);
        DB::table('regencys')->insert([ 'regency_code'=>6474, 'province_code'=>64, 'regency_name'=>'KOTA BONTANG']);
        DB::table('regencys')->insert([ 'regency_code'=>6501, 'province_code'=>65, 'regency_name'=>'KABUPATEN MALINAU']);
        DB::table('regencys')->insert([ 'regency_code'=>6502, 'province_code'=>65, 'regency_name'=>'KABUPATEN BULUNGAN']);
        DB::table('regencys')->insert([ 'regency_code'=>6503, 'province_code'=>65, 'regency_name'=>'KABUPATEN TANA TIDUNG']);
        DB::table('regencys')->insert([ 'regency_code'=>6504, 'province_code'=>65, 'regency_name'=>'KABUPATEN NUNUKAN']);
        DB::table('regencys')->insert([ 'regency_code'=>6571, 'province_code'=>65, 'regency_name'=>'KOTA TARAKAN']);
        DB::table('regencys')->insert([ 'regency_code'=>7101, 'province_code'=>71, 'regency_name'=>'KABUPATEN BOLAANG MONGONDOW']);
        DB::table('regencys')->insert([ 'regency_code'=>7102, 'province_code'=>71, 'regency_name'=>'KABUPATEN MINAHASA']);
        DB::table('regencys')->insert([ 'regency_code'=>7103, 'province_code'=>71, 'regency_name'=>'KABUPATEN KEPULAUAN SANGIHE']);
        DB::table('regencys')->insert([ 'regency_code'=>7104, 'province_code'=>71, 'regency_name'=>'KABUPATEN KEPULAUAN TALAUD']);
        DB::table('regencys')->insert([ 'regency_code'=>7105, 'province_code'=>71, 'regency_name'=>'KABUPATEN MINAHASA SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>7106, 'province_code'=>71, 'regency_name'=>'KABUPATEN MINAHASA UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>7107, 'province_code'=>71, 'regency_name'=>'KABUPATEN BOLAANG MONGONDOW UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>7108, 'province_code'=>71, 'regency_name'=>'KABUPATEN SIAU TAGULANDANG BIARO']);
        DB::table('regencys')->insert([ 'regency_code'=>7109, 'province_code'=>71, 'regency_name'=>'KABUPATEN MINAHASA TENGGARA']);
        DB::table('regencys')->insert([ 'regency_code'=>7110, 'province_code'=>71, 'regency_name'=>'KABUPATEN BOLAANG MONGONDOW SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>7111, 'province_code'=>71, 'regency_name'=>'KABUPATEN BOLAANG MONGONDOW TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>7171, 'province_code'=>71, 'regency_name'=>'KOTA MANADO']);
        DB::table('regencys')->insert([ 'regency_code'=>7172, 'province_code'=>71, 'regency_name'=>'KOTA BITUNG']);
        DB::table('regencys')->insert([ 'regency_code'=>7173, 'province_code'=>71, 'regency_name'=>'KOTA TOMOHON']);
        DB::table('regencys')->insert([ 'regency_code'=>7174, 'province_code'=>71, 'regency_name'=>'KOTA KOTAMOBAGU']);
        DB::table('regencys')->insert([ 'regency_code'=>7201, 'province_code'=>72, 'regency_name'=>'KABUPATEN BANGGAI KEPULAUAN']);
        DB::table('regencys')->insert([ 'regency_code'=>7202, 'province_code'=>72, 'regency_name'=>'KABUPATEN BANGGAI']);
        DB::table('regencys')->insert([ 'regency_code'=>7203, 'province_code'=>72, 'regency_name'=>'KABUPATEN MOROWALI']);
        DB::table('regencys')->insert([ 'regency_code'=>7204, 'province_code'=>72, 'regency_name'=>'KABUPATEN POSO']);
        DB::table('regencys')->insert([ 'regency_code'=>7205, 'province_code'=>72, 'regency_name'=>'KABUPATEN DONGGALA']);
        DB::table('regencys')->insert([ 'regency_code'=>7206, 'province_code'=>72, 'regency_name'=>'KABUPATEN TOLI-TOLI']);
        DB::table('regencys')->insert([ 'regency_code'=>7207, 'province_code'=>72, 'regency_name'=>'KABUPATEN BUOL']);
        DB::table('regencys')->insert([ 'regency_code'=>7208, 'province_code'=>72, 'regency_name'=>'KABUPATEN PARIGI MOUTONG']);
        DB::table('regencys')->insert([ 'regency_code'=>7209, 'province_code'=>72, 'regency_name'=>'KABUPATEN TOJO UNA-UNA']);
        DB::table('regencys')->insert([ 'regency_code'=>7210, 'province_code'=>72, 'regency_name'=>'KABUPATEN SIGI']);
        DB::table('regencys')->insert([ 'regency_code'=>7211, 'province_code'=>72, 'regency_name'=>'KABUPATEN BANGGAI LAUT']);
        DB::table('regencys')->insert([ 'regency_code'=>7212, 'province_code'=>72, 'regency_name'=>'KABUPATEN MOROWALI UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>7271, 'province_code'=>72, 'regency_name'=>'KOTA PALU']);
        DB::table('regencys')->insert([ 'regency_code'=>7301, 'province_code'=>73, 'regency_name'=>'KABUPATEN KEPULAUAN SELAYAR']);
        DB::table('regencys')->insert([ 'regency_code'=>7302, 'province_code'=>73, 'regency_name'=>'KABUPATEN BULUKUMBA']);
        DB::table('regencys')->insert([ 'regency_code'=>7303, 'province_code'=>73, 'regency_name'=>'KABUPATEN BANTAENG']);
        DB::table('regencys')->insert([ 'regency_code'=>7304, 'province_code'=>73, 'regency_name'=>'KABUPATEN JENEPONTO']);
        DB::table('regencys')->insert([ 'regency_code'=>7305, 'province_code'=>73, 'regency_name'=>'KABUPATEN TAKALAR']);
        DB::table('regencys')->insert([ 'regency_code'=>7306, 'province_code'=>73, 'regency_name'=>'KABUPATEN GOWA']);
        DB::table('regencys')->insert([ 'regency_code'=>7307, 'province_code'=>73, 'regency_name'=>'KABUPATEN SINJAI']);
        DB::table('regencys')->insert([ 'regency_code'=>7308, 'province_code'=>73, 'regency_name'=>'KABUPATEN MAROS']);
        DB::table('regencys')->insert([ 'regency_code'=>7309, 'province_code'=>73, 'regency_name'=>'KABUPATEN PANGKAJENE DAN KEPULAUAN']);
        DB::table('regencys')->insert([ 'regency_code'=>7310, 'province_code'=>73, 'regency_name'=>'KABUPATEN BARRU']);
        DB::table('regencys')->insert([ 'regency_code'=>7311, 'province_code'=>73, 'regency_name'=>'KABUPATEN BONE']);
        DB::table('regencys')->insert([ 'regency_code'=>7312, 'province_code'=>73, 'regency_name'=>'KABUPATEN SOPPENG']);
        DB::table('regencys')->insert([ 'regency_code'=>7313, 'province_code'=>73, 'regency_name'=>'KABUPATEN WAJO']);
        DB::table('regencys')->insert([ 'regency_code'=>7314, 'province_code'=>73, 'regency_name'=>'KABUPATEN SIDENRENG RAPPANG']);
        DB::table('regencys')->insert([ 'regency_code'=>7315, 'province_code'=>73, 'regency_name'=>'KABUPATEN PINRANG']);
        DB::table('regencys')->insert([ 'regency_code'=>7316, 'province_code'=>73, 'regency_name'=>'KABUPATEN ENREKANG']);
        DB::table('regencys')->insert([ 'regency_code'=>7317, 'province_code'=>73, 'regency_name'=>'KABUPATEN LUWU']);
        DB::table('regencys')->insert([ 'regency_code'=>7318, 'province_code'=>73, 'regency_name'=>'KABUPATEN TANA TORAJA']);
        DB::table('regencys')->insert([ 'regency_code'=>7322, 'province_code'=>73, 'regency_name'=>'KABUPATEN LUWU UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>7325, 'province_code'=>73, 'regency_name'=>'KABUPATEN LUWU TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>7326, 'province_code'=>73, 'regency_name'=>'KABUPATEN TORAJA UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>7371, 'province_code'=>73, 'regency_name'=>'KOTA MAKASSAR']);
        DB::table('regencys')->insert([ 'regency_code'=>7372, 'province_code'=>73, 'regency_name'=>'KOTA PAREPARE']);
        DB::table('regencys')->insert([ 'regency_code'=>7373, 'province_code'=>73, 'regency_name'=>'KOTA PALOPO']);
        DB::table('regencys')->insert([ 'regency_code'=>7401, 'province_code'=>74, 'regency_name'=>'KABUPATEN BUTON']);
        DB::table('regencys')->insert([ 'regency_code'=>7402, 'province_code'=>74, 'regency_name'=>'KABUPATEN MUNA']);
        DB::table('regencys')->insert([ 'regency_code'=>7403, 'province_code'=>74, 'regency_name'=>'KABUPATEN KONAWE']);
        DB::table('regencys')->insert([ 'regency_code'=>7404, 'province_code'=>74, 'regency_name'=>'KABUPATEN KOLAKA']);
        DB::table('regencys')->insert([ 'regency_code'=>7405, 'province_code'=>74, 'regency_name'=>'KABUPATEN KONAWE SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>7406, 'province_code'=>74, 'regency_name'=>'KABUPATEN BOMBANA']);
        DB::table('regencys')->insert([ 'regency_code'=>7407, 'province_code'=>74, 'regency_name'=>'KABUPATEN WAKATOBI']);
        DB::table('regencys')->insert([ 'regency_code'=>7408, 'province_code'=>74, 'regency_name'=>'KABUPATEN KOLAKA UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>7409, 'province_code'=>74, 'regency_name'=>'KABUPATEN BUTON UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>7410, 'province_code'=>74, 'regency_name'=>'KABUPATEN KONAWE UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>7411, 'province_code'=>74, 'regency_name'=>'KABUPATEN KOLAKA TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>7412, 'province_code'=>74, 'regency_name'=>'KABUPATEN KONAWE KEPULAUAN']);
        DB::table('regencys')->insert([ 'regency_code'=>7413, 'province_code'=>74, 'regency_name'=>'KABUPATEN MUNA BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>7414, 'province_code'=>74, 'regency_name'=>'KABUPATEN BUTON TENGAH']);
        DB::table('regencys')->insert([ 'regency_code'=>7415, 'province_code'=>74, 'regency_name'=>'KABUPATEN BUTON SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>7471, 'province_code'=>74, 'regency_name'=>'KOTA KENDARI']);
        DB::table('regencys')->insert([ 'regency_code'=>7472, 'province_code'=>74, 'regency_name'=>'KOTA BAUBAU']);
        DB::table('regencys')->insert([ 'regency_code'=>7501, 'province_code'=>75, 'regency_name'=>'KABUPATEN BOALEMO']);
        DB::table('regencys')->insert([ 'regency_code'=>7502, 'province_code'=>75, 'regency_name'=>'KABUPATEN GORONTALO']);
        DB::table('regencys')->insert([ 'regency_code'=>7503, 'province_code'=>75, 'regency_name'=>'KABUPATEN POHUWATO']);
        DB::table('regencys')->insert([ 'regency_code'=>7504, 'province_code'=>75, 'regency_name'=>'KABUPATEN BONE BOLANGO']);
        DB::table('regencys')->insert([ 'regency_code'=>7505, 'province_code'=>75, 'regency_name'=>'KABUPATEN GORONTALO UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>7571, 'province_code'=>75, 'regency_name'=>'KOTA GORONTALO']);
        DB::table('regencys')->insert([ 'regency_code'=>7601, 'province_code'=>76, 'regency_name'=>'KABUPATEN MAJENE']);
        DB::table('regencys')->insert([ 'regency_code'=>7602, 'province_code'=>76, 'regency_name'=>'KABUPATEN POLEWALI MANDAR']);
        DB::table('regencys')->insert([ 'regency_code'=>7603, 'province_code'=>76, 'regency_name'=>'KABUPATEN MAMASA']);
        DB::table('regencys')->insert([ 'regency_code'=>7604, 'province_code'=>76, 'regency_name'=>'KABUPATEN MAMUJU']);
        DB::table('regencys')->insert([ 'regency_code'=>7605, 'province_code'=>76, 'regency_name'=>'KABUPATEN MAMUJU UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>7606, 'province_code'=>76, 'regency_name'=>'KABUPATEN MAMUJU TENGAH']);
        DB::table('regencys')->insert([ 'regency_code'=>8101, 'province_code'=>81, 'regency_name'=>'KABUPATEN MALUKU TENGGARA BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>8102, 'province_code'=>81, 'regency_name'=>'KABUPATEN MALUKU TENGGARA']);
        DB::table('regencys')->insert([ 'regency_code'=>8103, 'province_code'=>81, 'regency_name'=>'KABUPATEN MALUKU TENGAH']);
        DB::table('regencys')->insert([ 'regency_code'=>8104, 'province_code'=>81, 'regency_name'=>'KABUPATEN BURU']);
        DB::table('regencys')->insert([ 'regency_code'=>8105, 'province_code'=>81, 'regency_name'=>'KABUPATEN KEPULAUAN ARU']);
        DB::table('regencys')->insert([ 'regency_code'=>8106, 'province_code'=>81, 'regency_name'=>'KABUPATEN SERAM BAGIAN BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>8107, 'province_code'=>81, 'regency_name'=>'KABUPATEN SERAM BAGIAN TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>8108, 'province_code'=>81, 'regency_name'=>'KABUPATEN MALUKU BARAT DAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>8109, 'province_code'=>81, 'regency_name'=>'KABUPATEN BURU SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>8171, 'province_code'=>81, 'regency_name'=>'KOTA AMBON']);
        DB::table('regencys')->insert([ 'regency_code'=>8172, 'province_code'=>81, 'regency_name'=>'KOTA TUAL']);
        DB::table('regencys')->insert([ 'regency_code'=>8201, 'province_code'=>82, 'regency_name'=>'KABUPATEN HALMAHERA BARAT']);
        DB::table('regencys')->insert([ 'regency_code'=>8202, 'province_code'=>82, 'regency_name'=>'KABUPATEN HALMAHERA TENGAH']);
        DB::table('regencys')->insert([ 'regency_code'=>8203, 'province_code'=>82, 'regency_name'=>'KABUPATEN KEPULAUAN SULA']);
        DB::table('regencys')->insert([ 'regency_code'=>8204, 'province_code'=>82, 'regency_name'=>'KABUPATEN HALMAHERA SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>8205, 'province_code'=>82, 'regency_name'=>'KABUPATEN HALMAHERA UTARA']);
        DB::table('regencys')->insert([ 'regency_code'=>8206, 'province_code'=>82, 'regency_name'=>'KABUPATEN HALMAHERA TIMUR']);
        DB::table('regencys')->insert([ 'regency_code'=>8207, 'province_code'=>82, 'regency_name'=>'KABUPATEN PULAU MOROTAI']);
        DB::table('regencys')->insert([ 'regency_code'=>8208, 'province_code'=>82, 'regency_name'=>'KABUPATEN PULAU TALIABU']);
        DB::table('regencys')->insert([ 'regency_code'=>8271, 'province_code'=>82, 'regency_name'=>'KOTA TERNATE']);
        DB::table('regencys')->insert([ 'regency_code'=>8272, 'province_code'=>82, 'regency_name'=>'KOTA TIDORE KEPULAUAN']);
        DB::table('regencys')->insert([ 'regency_code'=>9101, 'province_code'=>91, 'regency_name'=>'KABUPATEN FAKFAK']);
        DB::table('regencys')->insert([ 'regency_code'=>9102, 'province_code'=>91, 'regency_name'=>'KABUPATEN KAIMANA']);
        DB::table('regencys')->insert([ 'regency_code'=>9103, 'province_code'=>91, 'regency_name'=>'KABUPATEN TELUK WONDAMA']);
        DB::table('regencys')->insert([ 'regency_code'=>9104, 'province_code'=>91, 'regency_name'=>'KABUPATEN TELUK BINTUNI']);
        DB::table('regencys')->insert([ 'regency_code'=>9105, 'province_code'=>91, 'regency_name'=>'KABUPATEN MANOKWARI']);
        DB::table('regencys')->insert([ 'regency_code'=>9106, 'province_code'=>91, 'regency_name'=>'KABUPATEN SORONG SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>9107, 'province_code'=>91, 'regency_name'=>'KABUPATEN SORONG']);
        DB::table('regencys')->insert([ 'regency_code'=>9108, 'province_code'=>91, 'regency_name'=>'KABUPATEN RAJA AMPAT']);
        DB::table('regencys')->insert([ 'regency_code'=>9109, 'province_code'=>91, 'regency_name'=>'KABUPATEN TAMBRAUW']);
        DB::table('regencys')->insert([ 'regency_code'=>9110, 'province_code'=>91, 'regency_name'=>'KABUPATEN MAYBRAT']);
        DB::table('regencys')->insert([ 'regency_code'=>9111, 'province_code'=>91, 'regency_name'=>'KABUPATEN MANOKWARI SELATAN']);
        DB::table('regencys')->insert([ 'regency_code'=>9112, 'province_code'=>91, 'regency_name'=>'KABUPATEN PEGUNUNGAN ARFAK']);
        DB::table('regencys')->insert([ 'regency_code'=>9171, 'province_code'=>91, 'regency_name'=>'KOTA SORONG']);
        DB::table('regencys')->insert([ 'regency_code'=>9401, 'province_code'=>94, 'regency_name'=>'KABUPATEN MERAUKE']);
        DB::table('regencys')->insert([ 'regency_code'=>9402, 'province_code'=>94, 'regency_name'=>'KABUPATEN JAYAWIJAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>9403, 'province_code'=>94, 'regency_name'=>'KABUPATEN JAYAPURA']);
        DB::table('regencys')->insert([ 'regency_code'=>9404, 'province_code'=>94, 'regency_name'=>'KABUPATEN NABIRE']);
        DB::table('regencys')->insert([ 'regency_code'=>9408, 'province_code'=>94, 'regency_name'=>'KABUPATEN KEPULAUAN YAPEN']);
        DB::table('regencys')->insert([ 'regency_code'=>9409, 'province_code'=>94, 'regency_name'=>'KABUPATEN BIAK NUMFOR']);
        DB::table('regencys')->insert([ 'regency_code'=>9410, 'province_code'=>94, 'regency_name'=>'KABUPATEN PANIAI']);
        DB::table('regencys')->insert([ 'regency_code'=>9411, 'province_code'=>94, 'regency_name'=>'KABUPATEN PUNCAK JAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>9412, 'province_code'=>94, 'regency_name'=>'KABUPATEN MIMIKA']);
        DB::table('regencys')->insert([ 'regency_code'=>9413, 'province_code'=>94, 'regency_name'=>'KABUPATEN BOVEN DIGOEL']);
        DB::table('regencys')->insert([ 'regency_code'=>9414, 'province_code'=>94, 'regency_name'=>'KABUPATEN MAPPI']);
        DB::table('regencys')->insert([ 'regency_code'=>9415, 'province_code'=>94, 'regency_name'=>'KABUPATEN ASMAT']);
        DB::table('regencys')->insert([ 'regency_code'=>9416, 'province_code'=>94, 'regency_name'=>'KABUPATEN YAHUKIMO']);
        DB::table('regencys')->insert([ 'regency_code'=>9417, 'province_code'=>94, 'regency_name'=>'KABUPATEN PEGUNUNGAN BINTANG']);
        DB::table('regencys')->insert([ 'regency_code'=>9418, 'province_code'=>94, 'regency_name'=>'KABUPATEN TOLIKARA']);
        DB::table('regencys')->insert([ 'regency_code'=>9419, 'province_code'=>94, 'regency_name'=>'KABUPATEN SARMI']);
        DB::table('regencys')->insert([ 'regency_code'=>9420, 'province_code'=>94, 'regency_name'=>'KABUPATEN KEEROM']);
        DB::table('regencys')->insert([ 'regency_code'=>9426, 'province_code'=>94, 'regency_name'=>'KABUPATEN WAROPEN']);
        DB::table('regencys')->insert([ 'regency_code'=>9427, 'province_code'=>94, 'regency_name'=>'KABUPATEN SUPIORI']);
        DB::table('regencys')->insert([ 'regency_code'=>9428, 'province_code'=>94, 'regency_name'=>'KABUPATEN MAMBERAMO RAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>9429, 'province_code'=>94, 'regency_name'=>'KABUPATEN NDUGA']);
        DB::table('regencys')->insert([ 'regency_code'=>9430, 'province_code'=>94, 'regency_name'=>'KABUPATEN LANNY JAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>9431, 'province_code'=>94, 'regency_name'=>'KABUPATEN MAMBERAMO TENGAH']);
        DB::table('regencys')->insert([ 'regency_code'=>9432, 'province_code'=>94, 'regency_name'=>'KABUPATEN YALIMO']);
        DB::table('regencys')->insert([ 'regency_code'=>9433, 'province_code'=>94, 'regency_name'=>'KABUPATEN PUNCAK']);
        DB::table('regencys')->insert([ 'regency_code'=>9434, 'province_code'=>94, 'regency_name'=>'KABUPATEN DOGIYAI']);
        DB::table('regencys')->insert([ 'regency_code'=>9435, 'province_code'=>94, 'regency_name'=>'KABUPATEN INTAN JAYA']);
        DB::table('regencys')->insert([ 'regency_code'=>9436, 'province_code'=>94, 'regency_name'=>'KABUPATEN DEIYAI']);
        DB::table('regencys')->insert([ 'regency_code'=>9471, 'province_code'=>94, 'regency_name'=>'KOTA JAYAPURA']);

    }
}
